import { StyleSheet } from 'react-native';
import Colors from '../../../theme/colors';

export default StyleSheet.create({
  ProfileTabView: {
    flexDirection: 'row',
    marginHorizontal: 24,
    marginTop: 28,
    alignItems: 'center',
  },
  saveText: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginTop: 30,
    alignSelf: 'center',
    fontSize: 18,
  },
  errorText: {
    color: Colors.errorTextColor,
    marginHorizontal: 55,
    marginTop: 2,
    fontFamily: 'Oswald Light',
    fontSize: 12,
    fontWeight: '300',
    alignSelf: 'flex-start',
  },
  ProfileImage: {
    height: 60,
    backgroundColor: Colors.iconBgColor,
    width: 60,
    borderRadius: 60,
    borderColor: Colors.White,
    borderWidth: 0.56,
  },
  modelStyle: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.blurModelColor,
  },
  modelView: {
    borderColor: Colors.labelBgColor,
    borderWidth: 0.8,
    height: 178,
    width: 268,
    backgroundColor: Colors.modelColor,
  },
  changeTxt: {
    color: Colors.changeTxtColor,
    marginVertical: 10,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 14,
    marginHorizontal: 20,
  },
  takeTxt: {
    color: Colors.White,
    marginBottom: 10,
    marginHorizontal: 20,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 16,
  },
  galleryTxt: {
    color: Colors.White,
    marginBottom: 10,
    marginHorizontal: 20,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 16,
  },
  cancelTxt: {
    color: Colors.cancelTxtColor,
    marginHorizontal: 20,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 16,
  },
  userNameView: {
    marginLeft: 20,
    alignSelf: 'center',
    marginRight: 48,
  },
  userNameText: {
    fontFamily: 'Oswald Bold',
    fontWeight: '900',
    fontSize: 24,
    color: Colors.White,
  },
  mailIconView: {
    flexDirection: 'row',
    marginHorizontal: 25,
    alignItems: 'center',
  },
  phoneIconView: {
    flexDirection: 'row',
    marginHorizontal: 25,
    marginTop: 10,
    alignItems: 'center',
  },
  phoneNoInputStyle: {
    color: Colors.White,
    height: 40,
  },
  gridView: {
    flexDirection: 'row',
    height: 80,
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  followersCount: {
    fontFamily: 'Oswald Bold',
    fontWeight: '900',
    fontSize: 18,
    color: Colors.White,
  },
  logoutText: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 16,
    color: Colors.White,
    marginLeft: 24,
    marginTop: 12,
  },
  FollowingText: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 12,
    color: Colors.White,
  },
  FollowingCount: {
    fontFamily: 'Oswald Bold',
    fontWeight: '900',
    fontSize: 18,
    color: Colors.White,
  },
  followersText: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 12,
    color: Colors.White,
  },
  errorTextStyle: {
    fontFamily: 'Oswald Light',
    fontSize: 12,
    marginTop: 6,
    fontWeight: '300',
    alignSelf: 'flex-start',
    color: Colors.errorTextColor,
  },
  descriptionText: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 12,
    color: Colors.White,
  },
  editIconStyle: {
    marginTop: -18,
    marginLeft: 42,
    backgroundColor: Colors.URbtnColor,
    height: 18,
    width: 18,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialPlatformTitle: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginTop: 12,
    fontSize: 14,
    color: Colors.eventDetailsTextColor,
  },
  socialPlatform: {
    marginTop: 15,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 12,
    color: Colors.sideHeadingText,
  },
  socialPlatformUserId: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginBottom: 5,
    fontSize: 14,
    color: Colors.labelColor,
  },
});
