import { StyleSheet, Platform } from 'react-native';
import Colors from '../../theme/colors';

export default StyleSheet.create({
  textInput: {
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 14,
    height: 50,
    borderWidth: 1,
    width: '85%',
    padding: 10,
    marginHorizontal: 24,
    borderColor: Colors.textColor,
  },
  textInputProps: {
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 14,
    height: 50,
    padding: 10,
    borderWidth: 1,
    borderColor: Colors.textColor,
  },
  stylesInput: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: Colors.textColor,
  },
  stylesContainer: {
    position: 'relative',
    margin: 0,
    width: '85%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    marginHorizontal: 24,
  },
  stylesItemText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 12,
    color: Colors.labelColor,
  },
  stylesList: {
    marginTop: 5,
    backgroundColor: Colors.eventViewBgColor,
  },
  chipView: {
    marginHorizontal: 24,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chipContainer: {
    flexDirection: 'row',
    marginRight: 15,
    marginBottom: 12,
  },
  toggleView: { marginTop: 10, maxHeight: '55%' },
  selectGenrText: {
    marginTop: 15,
    marginLeft: 25,
    marginBottom: 25,
    fontSize: 24,
    fontFamily: 'Oswald Bold',
    fontWeight: '900',
    color: Colors.labelColor,
  },
  selectPickText: {
    marginTop: 15,
    marginLeft: 25,
    fontSize: 10,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.sideHeadingText,
  },
  indicationTextView: {
    width: '85%',
    marginTop: 5,
    maxHeight: '22%',
    alignSelf: 'center',
    backgroundColor: Colors.eventViewBgColor,
  },
  indicationText: {
    color: Colors.White,
    marginVertical: 10,
    marginLeft: 10,
  },
  errorText: {
    fontFamily: 'Oswald Light',
    fontSize: 12,
    marginTop: 6,
    width: '85%',
    alignSelf: 'center',
    fontWeight: '300',
    color: Colors.errorTextColor,
  },
  cityText: {
    marginVertical: 10,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 12,
    color: Colors.labelColor,
    marginHorizontal: 10,
  },
  conatiner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
  focusedStyle: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 16,
    width: 120,
    textAlign: 'center',
    paddingVertical: 6,
    color: Colors.URbtnColor,
  },
  unfocusedStyle: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 16,
    width: 120,
    textAlign: 'center',
    paddingVertical: 6,
    color: Colors.sideHeadingText,
  },
  inputBox: {
    borderWidth: 1,
    width: '85%',
    alignSelf: 'center',
  },
  inputText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 14,
    marginVertical: Platform.OS === 'ios' ? 4 : 0,
    color: Colors.labelColor,
  },
  genrTextView: {
    marginTop: 12,
    height: 22,
    backgroundColor: Colors.genrBgColor,
    justifyContent: 'center',
    marginLeft: 18,
    borderRadius: 2,
  },
  chiBtnStyle: {
    borderWidth: 1,
    padding: 5,
  },
  genrText: {
    marginHorizontal: 8,
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 14,
  },
  bgImgStyle: {
    marginHorizontal: 24,
    marginBottom: 24,
    borderRadius: 2,
  },
  LinearGradientStyle: {
    height: 135,
    borderRadius: 2,
  },
  titleStyle: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.Black,
  },
  buttonStyle: {
    backgroundColor: Colors.eventNameTextColor,
    width: '100%',
    borderRadius: 0,
  },
  containerStyle: {
    borderRadius: 0,
    width: '88%',
    alignSelf: 'center',
    paddingTop: 20,
  },
  selectText: {
    marginHorizontal: 24,
    fontSize: 24,
    fontFamily: 'Oswald Bold',
    fontWeight: '900',
    marginBottom: 18,
    color: Colors.labelColor,
  },
  circleButtons: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  uncheckedIcon: {
    height: 19,
    width: 19,
  },
  checkedIcon: {
    height: 22,
    width: 20,
  },
  checkBoxcontainerStyle: {
    marginLeft: 0,
    marginRight: 0,
    padding: 0,
  },
  includeText: {
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 8,
    color: Colors.labelColor,
  },
  genrNameText: {
    fontWeight: '800',
    fontFamily: 'Oswald Bold',
    fontSize: 18,
    color: Colors.labelColor,
  },
  flatListView: {
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});

