import { StyleSheet, Platform } from 'react-native';
import Colors from '../../theme/colors';

export default StyleSheet.create({
  genresArtistTextStyle: {
    fontSize: 16,
    fontFamily: 'Oswald Bold',
    fontWeight: '800',
    alignSelf: 'center',
    color: Colors.White,
    marginVertical: 10,
  },
  genresNameTextStyle: {
    fontSize: 16,
    fontFamily: 'Oswald Bold',
    fontWeight: '500',
    color: Colors.White,
    marginBottom: 15,
  },
  genresNameView: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: Colors.genreOverlay,
    height: 130,
    width: 130,
  },
  imageBackgroundStyle: {
    height: 130,
    width: 130,
  },
  imageBackgroundView: {
    marginHorizontal: 25,
    width: 130,
  },
  artistGenresListView: {
    flexDirection: 'row',
    marginVertical: 15,
    justifyContent: 'center',
  },
  popularArtistGenresText: {
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '600',
    fontSize: 20,
    marginLeft: 25,
    marginTop: 10,
  },
  popularArtistGenresView: {
    backgroundColor: Colors.statisticsBgColor,
    marginBottom: 20,
  },
  popularArtistUserText: {
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '600',
    fontSize: 18,
  },
  popularArtistUserTextView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  popularArtistText: {
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '600',
    fontSize: 20,
    marginLeft: 25,
    marginTop: 10,
  },
  popularArtistView: {
    backgroundColor: Colors.statisticsBgColor,
    marginBottom: 20,
  },
  radioStationLocationText: {
    fontSize: 14,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.White,
    marginBottom: 6,
  },
  radioStationLocationView: {
    flex: 1,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  circleRadioStation: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.Black,
  },
  countText: {
    fontSize: 20,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    color: Colors.Black,
  },
  radioStationCircleRing5: {
    backgroundColor: 'rgba(255, 208, 70, 1)',
    alignItems: 'center',
    height: 84,
    width: 84,
    borderRadius: 84,
    justifyContent: 'center',
  },
  radioStationCircleRing4: {
    backgroundColor: 'rgba(255, 208, 70, 0.18)',
    alignItems: 'center',
    height: 94,
    width: 94,
    borderRadius: 94,
    justifyContent: 'center',
  },
  radioStationCircleRing3: {
    alignItems: 'center',
    height: 103,
    width: 103,
    borderRadius: 103,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 208, 70, 1)',
  },
  radioStationCircleRing2: {
    alignItems: 'center',
    height: 115,
    width: 115,
    borderRadius: 115,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 208, 70, 0.4)',
  },
  radioStationCircleRing1: {
    alignItems: 'center',
    height: 128,
    width: 128,
    borderRadius: 128,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 208, 70, 0.2)',
  },
  radioStationCircleView: {
    alignItems: 'center',
    marginLeft: 20,
  },
  radioStationView: {
    flexDirection: 'row',
    marginVertical: 20,
  },
  renderRadioStationCardContainerStyle: {
    backgroundColor: Colors.statisticsBgColor,
    marginBottom: 20,
  },
  radioStationText: {
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '600',
    fontSize: 20,
    marginLeft: 25,
    marginTop: 10,
  },
  miniPlayerStyle: {
    height: 150,
    backgroundColor: Colors.Black,
  },
  AllAlbumsView: {
    height: Platform.OS === 'ios' ? '87%' : '85%',
    justifyContent: 'space-between',
  },
  gridView: {
    marginBottom: 10,
    flexDirection: 'row',
  },
  AllAlbumsContainer: {
    height: '85%',
  },
  ratedImageView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginVertical: 10,
  },
  ratedImage: {
    height: 73,
    width: 70,
  },
  ratedDayTextStyle: {
    fontSize: 12,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    color: Colors.profileIconColor,
  },
  ratedTextView: { marginLeft: 12, alignSelf: 'center' },
  ratedTextStyle: {
    fontSize: 16,
    width: '65%',
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    color: Colors.White,
  },
  ratedNameView: {
    flexDirection: 'row',
    width: '23%',
    alignItems: 'center',
    marginTop: 2,
  },
  ratedTitle: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    width: '65%',
    fontWeight: '400',
    color: Colors.AlbumTitleColor,
  },
  ratedView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: 24,
  },
  ratedText: {
    fontSize: 20,
    marginLeft: 24,
    fontFamily: 'Oswald Bold',
    fontWeight: '800',
    color: Colors.White,
  },
  albumsImageView: {
    marginHorizontal: 7,
    width: 148,
    marginVertical: 10,
  },
  albumsImage: {
    height: 148,
    width: 148,
  },
  albumsTextStyle: {
    marginTop: 8,
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.labelColor,
  },
  AlbumNameView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  AlbumTitle: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.AlbumTitleColor,
  },
  illustrationStyle: {
    height: 242,
    width: 252,
  },
  AlbumsView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: 24,
  },
  AlbumsText: {
    fontSize: 20,
    marginLeft: 24,
    fontFamily: 'Oswald Bold',
    fontWeight: '800',
    color: Colors.White,
  },
  memberImageView: {
    alignItems: 'center',
    marginRight: 28,
    width: 80,
    marginVertical: 14,
  },
  memberImageStyle: {
    height: 80,
    width: 80,
    backgroundColor: Colors.iconBgColor,
    borderRadius: 80,
  },
  memberTextStyle: {
    textAlign: 'center',
    marginTop: 14,
    fontSize: 14,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.labelColor,
  },
  seeallText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 12,
    color: Colors.labelColor,
  },
  promosImage: {
    height: 145,
    width: '100%',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  promosText: {
    marginTop: 12,
    fontWeight: '800',
    fontFamily: 'Oswald Bold',
    fontSize: 24,
    color: Colors.labelColor,
  },
  bandName: {
    color: Colors.eventNameTextColor,
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 16,
  },
  bandNameHeadeing: {
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 14,
    color: Colors.eventDetailsTextColor,
  },
});
