import { StyleSheet, Platform } from 'react-native';
import Colors from '../../theme/colors';

export default StyleSheet.create({
  container: {
    height: Platform.OS === 'ios' ? '87%' : '85%',
    justifyContent: 'space-between',
  },
  miniPlayerView: {
    height: 150,
    backgroundColor: Colors.Black,
  },
  promosView: {
    marginTop: 11,
    backgroundColor: Colors.eventViewBgColor,
    marginBottom: 20,
    borderRadius: 4,
  },
  promosImage: {
    height: 171,
    width: '100%',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  promosText: {
    fontFamily: 'Oswald Bold',
    fontWeight: '800',
    fontSize: 16,
    color: Colors.labelColor,
  },
  BandList: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 16,
    color: Colors.sideHeadingText,
  },
  socialPlatformTitle: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginTop: 12,
    marginBottom: 10,
    fontSize: 14,
    color: Colors.eventDetailsTextColor,
  },
  socialPlatformUserId: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginBottom: 5,
    fontSize: 14,
    color: Colors.labelColor,
  },
  membersImageView: {
    alignItems: 'center',
    marginHorizontal: 7,
    width: 148,
    marginVertical: 10,
  },
  membersImageStyle: {
    height: 148,
    width: 148,
  },
  membersText: {
    color: Colors.White,
    textAlign: 'center',
    marginTop: 8,
  },
  profileImageView: {
    marginTop: 20,
    marginBottom: 20,
  },
  profileImage: {
    width: 96,
    height: 96,
    backgroundColor: Colors.iconBgColor,
    borderRadius: 96,
    alignSelf: 'center',
  },
  profileName: {
    marginTop: 8,
    alignSelf: 'center',
    color: Colors.White,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 16,
  },
  followBtnView: {
    backgroundColor: Colors.URbtnColor,
    borderRadius: 20,
    alignItems: 'center',
    width: 98,
    alignSelf: 'center',
    marginVertical: 10,
  },
  unfollowBtnView: {
    backgroundColor: Colors.URbtnBgColor,
    borderRadius: 20,
    alignItems: 'center',
    width: 98,
    alignSelf: 'center',
    marginVertical: 10,
  },
  followBtn: {
    marginVertical: 5,
    marginHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  unfollowText: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginLeft: 5,
    color: Colors.White,
  },
  followText: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    marginLeft: 5,
    color: Colors.Black,
  },
  appearsText: {
    marginTop: 20,
    color: Colors.sideHeadingText,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 18,
  },
  bandNameView: {
    marginHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
  },
  btnView: {
    backgroundColor: Colors.URbtnColor,
    borderRadius: 20,
    alignItems: 'center',
  },
  unfollowbtn: {
    backgroundColor: Colors.URbtnBgColor,
    borderRadius: 20,
    alignItems: 'center',
  },
  seeallText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 12,
    color: Colors.labelColor,
  },
  socialPlatform: {
    marginTop: 20,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 12,
    color: Colors.sideHeadingText,
  },
  bandListView: {
    marginHorizontal: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
