import { StyleSheet } from 'react-native';
import Colors from '../../theme/colors';

export default StyleSheet.create({
  imageView: {
    height: 140,
    width: '100%',
  },
  popUpContainer: {
    backgroundColor: Colors.popUpContainerColor,
    marginHorizontal: 30,
    width: '85%',
  },
  modelView: {
    marginVertical: 16,
    backgroundColor: Colors.URbtnColor,
    borderRadius: 20,
    width: 100,
    alignSelf: 'center',
  },
  popUpView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.blurModelColor,
  },
  closeBtn: {
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 14,
    color: Colors.Black,
    marginVertical: 6,
    alignSelf: 'center',
  },
  newRelease: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 22,
    color: Colors.labelColor,
  },
  svgTxt: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 18,
    color: Colors.labelColor,
    width: 150,
    position: 'absolute',
    textAlign: 'center',
    left: 0,
    right: 0,
    top: '68%',
    bottom: '12%',
  },
  radioStaion: {
    marginBottom: 10,
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 22,
    color: Colors.labelColor,
  },
  radioStaionView: {
    marginBottom: 25,
    marginLeft: 20,
  },
  albumsImageView: {
    width: 148,
    marginRight: 15,
    marginVertical: 10,
  },
  albumsImage: {
    height: 148,
    width: 148,
  },
  albumsTextStyle: {
    marginTop: 8,
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.labelColor,
  },
  AlbumNameView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  AlbumTitle: {
    fontSize: 12,
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    color: Colors.AlbumTitleColor,
  },
  AlbumsView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: 24,
  },
  AlbumsText: {
    fontSize: 20,
    marginLeft: 24,
    fontFamily: 'Oswald Bold',
    fontWeight: '800',
    color: Colors.White,
  },
  feedContainerView: {
    backgroundColor: Colors.feedContainerViewColor,
    marginBottom: 20,
  },
  illustrationStyle: {
    height: 230,
    width: 238,
  },
  feedProfileView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  feedProfile: {
    height: 26,
    width: 26,
    borderRadius: 26,
    marginRight: 12,
    backgroundColor: Colors.iconBgColor,
  },
  eventBandName: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 14,
    color: Colors.White,
    textTransform: 'capitalize',
  },
  songTitle: {
    color: Colors.heighlatedColor,
    textTransform: 'capitalize',
  },
  feedText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 14,
    color: Colors.White,
  },
  welcomeText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '600',
    fontSize: 22,
    color: Colors.radiumColour,
  },
  followText: {
    fontFamily: 'Oswald Regular',
    fontWeight: '400',
    fontSize: 16,
    color: Colors.White,
  },
  feedTimeText: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 10,
    color: Colors.textColor,
  },
  feedClick: {
    fontFamily: 'Oswald Medium',
    fontWeight: '500',
    fontSize: 14,
    color: Colors.URbtnColor,
    textDecorationLine: 'underline',
  },
  viewStyle: {
    paddingBottom: '25%',
  },
  containtView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bandNameHeadeing: {
    color: Colors.eventNameTextColor,
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 16,
  },
  addCalendarBtnText: {
    marginVertical: 4,
    marginLeft: 3,
    fontFamily: 'Oswald Regular',
    color: Colors.labelColor,
    fontWeight: '400',
    fontSize: 10,
  },
  calendarBtnText: {
    marginHorizontal: 14,
    marginVertical: 4,
    fontFamily: 'Oswald Regular',
    color: Colors.labelColor,
    fontWeight: '400',
    fontSize: 10,
  },
  addedCalBtn: {
    marginHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  calendarBtnView: {
    backgroundColor: Colors.calendarBtnBg,
    borderRadius: 20,
    marginTop: 8,
  },
  eventTextView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  eventView: {
    marginHorizontal: 24,
    backgroundColor: Colors.eventViewBgColor,
    paddingBottom: 15,
    marginBottom: 25,
    borderRadius: 4,
  },
  eventText: {
    width: '60%',
    marginTop: 12,
    fontWeight: '800',
    fontFamily: 'Oswald Bold',
    fontSize: 24,
    color: Colors.labelColor,
  },
  eventDetailsTextView: {
    marginTop: 6,
    flexDirection: 'row',
  },
  eventImage: {
    height: 145,
    width: '100%',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  eventDetailsText: {
    color: Colors.eventDetailsTextColor,
    left: 8,
    fontWeight: '400',
    fontFamily: 'Oswald Regular',
    fontSize: 14,
  },
});
