name: Android Debug Build

on:
  push:
    branches: [ main, develop, android/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  android-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Set NODE_OPTIONS for Metro compatibility
      run: export NODE_OPTIONS=--openssl-legacy-provider
      
    - name: Build Android Debug APK
      run: |
        cd android
        ./gradlew --no-daemon clean assembleDebug
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        
    - name: Generate dependency report
      run: |
        cd android
        ./gradlew --no-daemon dependencies --configuration debugRuntimeClasspath > deps_debugRuntimeClasspath.txt
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload dependency report
      uses: actions/upload-artifact@v3
      with:
        name: deps-report
        path: android/deps_debugRuntimeClasspath.txt
        
    - name: Upload Gradle reports
      uses: actions/upload-artifact@v3
      with:
        name: gradle-reports
        path: android/app/build/reports/
        if-no-files-found: ignore
