name: Android Debug Build

on:
  push:
    branches: [ main, feat/ccpm-framework ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Sanity-check the wrapper is present & safe
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Make sure AGP has the exact SDK components it needs
      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install JS deps
        run: yarn install --frozen-lockfile

      # Ensure gradlew is executable and has LF endings on Linux runners
      - name: Prepare Gradle wrapper (Linux)
        working-directory: android
        run: |
          test -f gradlew || (echo "::error ::android/gradlew is missing"; exit 1)
          chmod +x gradlew
          sed -i 's/\r$//' gradlew

      - name: Print tool versions & tree
        working-directory: android
        run: |
          java -version
          node -v
          yarn -v
          ./gradlew -v
          echo "== android directory =="
          ls -la
          echo "== app directory =="
          ls -la app || true

      - name: Build Android Debug APK
        working-directory: android
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: ./gradlew --no-daemon --stacktrace --info clean assembleDebug

      # While diagnosing, don't fail the job on missing artifacts
      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Upload Gradle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            android/**/build/reports/**
            android/**/build/outputs/**/*
          if-no-files-found: warn

