name: Android Debug Build

on:
  push:
    branches: [ main, feat/ccpm-framework ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Normalize gradlew (LF + +x) for Linux CI
        run: |
          git config --global core.autocrlf false
          sed -i 's/\r$//' android/gradlew
          chmod +x android/gradlew

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install JS deps
        run: yarn --frozen-lockfile

      - name: Build Android Debug APK
        working-directory: android
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Upload Gradle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            android/**/build/reports/**
            android/**/build/outputs/**
          if-no-files-found: warn

