name: Android Debug Build

on:
  push:
    branches: [ main, feat/ccpm-framework ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install JS deps
        run: yarn install --frozen-lockfile

      - name: Make gradlew executable (Linux CI)
        working-directory: android
        run: |
          chmod +x gradlew
          # fix possible CRLF on Windows-committed wrapper
          sed -i 's/\r$//' gradlew

      - name: Print tool versions
        working-directory: android
        run: |
          java -version
          node -v
          yarn -v
          ./gradlew -v

      - name: Build Android Debug APK
        working-directory: android
        env:
          # keep Metro compatibility if RN scripts touch it
          NODE_OPTIONS: --openssl-legacy-provider
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Upload Gradle reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            android/**/build/reports/**
            android/**/build/outputs/**/*
          if-no-files-found: warn
